modLoader="javafml"
loaderVersion="[43,)"
license="Apache"
[[mods]]
modId="simplevoiceradio"
version="1.19.2-1.4.0.0"
displayName="Super Simple Voice Radio"
logoFile="icon.png"
credits=""
authors="ACCBDD"
description='''
This is a simple handheld radio addon created for the Dimensional Ascension modpack. It is an addon for the Simple Voice Chat mod.
'''
[[dependencies.simplevoiceradio]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplevoiceradio]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplevoiceradio]]
    modId="voicechat"
    mandatory=true
    versionRange="[1.19.2-2.4.32,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.simplevoiceradio]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.4.3,)"
    ordering="AFTER"
    side="BOTH"