modLoader="javafml"
loaderVersion="[43,)"
license="MIT"
[[mods]]
modId="simplevoiceradio"
version="1.19.2-1.0.0.0"
displayName="Simple Voice Mod Radio"
logoFile="icon.png"
credits=""
authors="ACCBDD"
description='''
A Simple Voice Chat Radio
'''
[[dependencies.simplevoiceradio]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplevoiceradio]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.simplevoiceradio]]
    modId="voicechat"
    mandatory=true
    versionRange="[1.19.2-2.4.32,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.simplevoiceradio]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.4.4,)"
    ordering="AFTER"
    side="BOTH"