modLoader="javafml"
loaderVersion="${forge_loader_requirement}"
license="MIT"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Example Mod"
logoFile="icon.png"
credits=""
authors="Example Author"
description='''
A Simple Voice Chat API mod example
'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_requirement}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="voicechat"
    mandatory=true
    versionRange="[${voicechat_dependency},)"
    ordering="AFTER"
    side="BOTH"